### ISSUE TITLE
icon-github.html error

### ISSUE THREAD

**Issue by alikrc** [acanimal/acanimal.github.io#3]
I just pulled and used jekyll serve but there is an error, how to solve this?
![image](https://cloud.githubusercontent.com/assets/2185905/23454028/d8d8954c-fe7b-11e6-8a0e-70d7760d6cac.png)

**Comment by acanimal** [comment]
Just updated this blog to use docker instead need to have locally installed ruby, jekyll and all the dependencies. Try and check if it solves the issue.
